components:
  admin-service:
    enabled: true
    envFrom:
    - secretRef:
        name: admin-service-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    port: 8000
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
    replicas: 1
    resources: &id001
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  api-gateway:
    enabled: true
    envFrom:
    - secretRef:
        name: api-gateway-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    port: 8000
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
    replicas: 1
    resources: *id001
  consumer-service:
    enabled: true
    envFrom:
    - secretRef:
        name: consumer-service-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    port: 8000
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
    replicas: 1
    resources: *id001
  merchant-service:
    enabled: true
    envFrom:
    - secretRef:
        name: merchant-service-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    port: 8000
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
    replicas: 1
    resources: *id001
