components:
  backend:
    enabled: true
    envFrom:
    - secretRef:
        name: backend-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 10
    port: 8000
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    replicas: 1
    resources: &id001
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  celery-beat:
    command:
    - celery
    - -A
    - config
    - beat
    - --loglevel=info
    enabled: true
    envFrom:
    - secretRef:
        name: celery-beat-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      tcpSocket:
        port: null
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      tcpSocket:
        port: null
    replicas: 1
    resources: *id001
  celery-worker:
    command:
    - celery
    - -A
    - config
    - worker
    - --loglevel=info
    enabled: true
    envFrom:
    - secretRef:
        name: celery-worker-env
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      tcpSocket:
        port: null
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      tcpSocket:
        port: null
    replicas: 1
    resources: *id001
  frontend:
    enabled: true
    envFrom:
    - secretRef:
        name: frontend-env
    image:
      repository: ''
      tag: latest
    port: 3000
    replicas: 1
    resources: *id001
