tenant:
  slug: oktradesystem-ddf98319
  namespace: t-oktradesystem-ddf98319-prod
  plan: starter
components:
  frontend:
    enabled: true
    type: frontend
    image:
      repository: ghcr.io/sunnepah/oktradesystem-frontend
      tag: main-a19b8d5
      pullPolicy: Always
    port: 3000
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    env: []
    command: []
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 3
  backend:
    enabled: true
    type: backend
    image:
      repository: ghcr.io/sunnepah/oktradesystem-backend
      tag: main-a19b8d5
      pullPolicy: Always
    port: 8000
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    env: []
    command: []
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 3
  worker:
    enabled: true
    type: worker
    image:
      repository: ghcr.io/sunnepah/oktradesystem-frontend
      tag: main-a19b8d5
      pullPolicy: Always
    port: 8000
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    env: []
    command: []
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 3
postgres:
  enabled: true
valkey:
  enabled: true
monitoring:
  enabled: false
secrets:
  enabled: true
