apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openproject-secret-key
  namespace: t-neo-internals-1dc0-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tenant-secret-store
    kind: SecretStore
  target:
    name: openproject-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret_key_base
      remoteRef:
        key: neo-internals-1dc0-prod
        property: OPENPROJECT_SECRET_KEY_BASE
