components: []
customDomain:
  enabled: false
  hostname: ""
database:
  mode: orbit
hpa:
  enabled: true
  maxReplicas: 50
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
ingress:
  enabled: true
  gatewayName: orbit-gateway
  gatewayNamespace: orbit-system
  hostname: neo-internals-1dc0-prod.orbit.lustres.dev
  tls: true
monitoring:
  enabled: true
  grafanaDashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
  serviceMonitor:
    interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 10s
pdb:
  enabled: true
  minAvailable: 1
postgres:
  database: appdb
  enabled: true
  existingSecret: tenant-db-credentials
  existingSecretKey: password
  instances: 1
  postgresUser: tenant
  storage:
    size: 50Gi
    storageClass: local-path
  version: "17"
secrets:
  enabled: false
tenant:
  namespace: t-neo-internals-1dc0-prod
  orgId: 79f99a82-41f8-4d4d-8103-30589731e620
  plan: scale
  resourcePrefix: t-neo-internals-1dc0-prod
  slug: neo-internals-1dc0-prod
valkey:
  enabled: false
