components:
  backend:
    enabled: true
    envFrom:
    - secretRef:
        name: tenant-secrets-backend
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: null
      initialDelaySeconds: 60
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: null
      initialDelaySeconds: 30
      periodSeconds: 10
    replicas: 1
    resources: &id001
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  celery-beat:
    enabled: true
    envFrom:
    - secretRef:
        name: tenant-secrets-celery-beat
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      tcpSocket:
        port: null
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      tcpSocket:
        port: null
    replicas: 1
    resources: *id001
  celery-worker:
    enabled: true
    envFrom:
    - secretRef:
        name: tenant-secrets-celery-worker
    image:
      repository: ''
      tag: latest
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      tcpSocket:
        port: null
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      tcpSocket:
        port: null
    replicas: 1
    resources: *id001
migration:
  command: python manage.py migrate --noinput
  enabled: true
