components:
  capp:
    enabled: false
    image:
      repository: ghcr.io/lustresconsulting/orbit-tenant-ecomlit-web-79cb-staging-capp
      tag: latest
    port: 3000
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    type: frontend
  mapp:
    enabled: true
    env:
    - name: NEXT_PUBLIC_API_URL
      value: https://merchant-service-ecomlit-api-5935-staging.orbit.lustres.dev/graphql
    image:
      repository: ghcr.io/lustresconsulting/orbit-tenant-ecomlit-web-79cb-staging-mapp
      tag: 55a489bd1cd7c86dab70504d702b4c72c442545f
    port: 3000
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    type: frontend
customDomain:
  enabled: false
  hostname: ""
database:
  mode: external
hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
ingress:
  enabled: true
  gatewayName: orbit-gateway
  gatewayNamespace: orbit-system
  hostname: ecomlit-web-79cb-staging.orbit.lustres.dev
  tls: true
monitoring:
  enabled: true
  grafanaDashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
  serviceMonitor:
    interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 10s
pdb:
  enabled: true
  minAvailable: 1
postgres:
  enabled: false
secrets:
  enabled: false
tenant:
  namespace: t-ecomlit-web-79cb-staging
  plan: starter
  resourcePrefix: t-ecomlit-web-79cb-staging
  slug: ecomlit-web-79cb-staging
valkey:
  enabled: false
