tenant:
  slug: ns1-task-0a34-staging
  namespace: t-ns1-task-0a34-staging
  resourcePrefix: t-ns1-task-0a34-staging
  plan: starter
  orgId: 1634917b-5c45-4d56-a8d5-9017cc56b7da
database:
  mode: orbit
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
pdb:
  enabled: true
  minAvailable: 1
postgres:
  enabled: true
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path
  existingSecret: tenant-db-credentials
  existingSecretKey: password
  postgresUser: tenant
  database: appdb
  version: '17'
valkey:
  enabled: true
  image:
    repository: valkey/valkey
    tag: 7.2-alpine
  storage:
    size: 1Gi
    storageClass: local-path
  existingSecret: tenant-valkey-credentials
  existingSecretKey: password
secrets:
  enabled: false
ingress:
  enabled: true
  hostname: ns1-task-0a34-staging.orbit.lustres.dev
  gatewayName: orbit-gateway
  gatewayNamespace: orbit-system
  tls: true
customDomain:
  enabled: false
  hostname: ''
monitoring:
  enabled: true
  serviceMonitor:
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    port: metrics
  grafanaDashboard:
    enabled: true
    labels:
      grafana_dashboard: '1'
components:
  api:
    image:
      repository: ghcr.io/lustresconsulting/orbit-tenant-ns1-task-0a34-staging-api
      tag: f221339d676d4017c05ee67deb7f9a84d9a7d961
