{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-app.appname" . }}
  namespace: {{ .Values.tenant.namespace }}
  labels:
    {{- include "tenant-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "tenant-app.appname" . }}
    app.kubernetes.io/component: app
  annotations:
    {{- toYaml .Values.app.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenant-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tenant-app.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "tenant-app.appname" . }}
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- if .Values.app.env }}
          env:
            {{- toYaml .Values.app.env | nindent 12 }}
          {{- end }}
          {{- if .Values.secrets.enabled }}
          envFrom:
            - secretRef:
                name: tenant-app-secrets
                optional: true
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: {{ .Values.app.readOnlyRootFilesystem | default false }}
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr-pull-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "tenant-app.selectorLabels" . | nindent 14 }}
{{- end }}
