{{- range $name, $comp := .Values.components }}
{{- if and $comp.enabled (ne $comp.type "worker") (ne ($comp.port | int) 0) }}
{{- $hostname := "" }}
{{- if eq $comp.type "frontend" }}
{{- $hostname = printf "%s.orbit.lustres.dev" $.Values.tenant.slug }}
{{- else }}
{{- $hostname = printf "api-%s.orbit.lustres.dev" $.Values.tenant.slug }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Values.tenant.slug }}-{{ $name }}
  namespace: {{ $.Values.tenant.namespace }}
  labels:
    orbit.sh/tenant: {{ $.Values.tenant.slug }}
    orbit.sh/component: {{ $comp.type }}
spec:
  parentRefs:
    - name: orbit-gateway
      namespace: orbit-system
      sectionName: websecure
  hostnames:
    - {{ $hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $.Values.tenant.slug }}-{{ $name }}
          port: {{ $comp.port }}
---
{{- end }}
{{- end }}
