{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-app-secrets
  namespace: {{ .Values.tenant.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: infisical-tenant
  target:
    name: tenant-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: REDIS_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: SECRET_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
{{- end }}
