{{- if .Values.secrets.enabled }}
{{- range $name, $comp := .Values.components }}
{{- if $comp.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-secrets-{{ $name }}
  namespace: {{ $.Values.tenant.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-orbit-tenants
  target:
    name: tenant-secrets-{{ $name }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /{{ .Values.tenant.slug }}/DATABASE_URL
{{- end }}
{{- end }}
{{- end }}

