{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-app-secrets
  namespace: {{ .Values.tenant.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-orbit-tenants
  target:
    name: tenant-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
        environmentSlug: prod
        secretsPath: /{{ .Values.tenant.slug }}
    - secretKey: REDIS_URL
      remoteRef:
        key: REDIS_URL
        environmentSlug: prod
        secretsPath: /{{ .Values.tenant.slug }}
    - secretKey: SECRET_KEY
      remoteRef:
        key: SECRET_KEY
        environmentSlug: prod
        secretsPath: /{{ .Values.tenant.slug }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
        environmentSlug: prod
        secretsPath: /{{ .Values.tenant.slug }}
{{- end }}
